checks:
    php: true

build_failure_conditions:
    - 'issues.severity(>= MAJOR).new.exists'
    - 'project.metric("scrutinizer.test_coverage", < 0.70)'
    - 'project.metric("scrutinizer.quality", < 9)'
    - 'project.metric_change("scrutinizer.quality", < -0.10)'
    - 'project.metric_change("scrutinizer.test_coverage", < -0.10)'

build:
    environment:
        php:
            version: 5.3.2
            ini:
                'error_reporting': 16383

    tests:
        override:
            -
                command: './vendor/bin/phpunit --coverage-clover=coverage-report'

                coverage:
                    file: 'coverage-report'
                    format: 'php-clover'

tools:
    external_code_coverage: false
    php_code_coverage:      false
    php_code_sniffer:
        config:
            standard: 'symfony'
    php_changetracking: true
    php_cpd: true
    php_cs_fixer:
        config:
            level: 'all'
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: true
    sensiolabs_security_checker: true

filter:
    excluded_paths:
        - 'Tests/'

coding_style:
    php:
        spaces:
            before_parentheses:
                closure_definition: true
            around_operators:
                concatenation: false
