language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
    - 5.3

matrix:
    allow_failures:
        - php: nightly
    fast_finish: true

before_script:
    - if [[ "$TRAVIS_PHP_VERSION" = "5.6" ]]; then wget http://get.sensiolabs.org/php-cs-fixer.phar; fi;

install:
    - composer self-update
    - composer install --no-interaction --prefer-dist --optimize-autoloader --verbose --ansi

script:
    - vendor/bin/phpunit
    - if [[ "$TRAVIS_PHP_VERSION" = "5.6" ]]; then php php-cs-fixer.phar fix --no-interaction --dry-run --diff -vvv; fi;
